services:
  dev-db:
    image: postgres
    env_file: .env
    networks:
      dev-net:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    env_file: .env

    ports:
      - 3000:3000
      - 5555:5555

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      dev-net:
        aliases:
          - app

networks:
  dev-net:

    # dev-app:
    #   image: backendapi:latest
    #   env_file: .env
    #   volumes:
    #     - ./images:/home/node/images
    #   ports:
    #     - '3000:3000'
