name: Renovate
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.0
        with:
          renovate-version: 35.0.0
          token: ${{ secrets.RENOVATE_TOKEN }}